import "./globals.css";
import { TanStackQueryClientProvider } from "@/lib/queryClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanStackQueryClientProvider>{children}</TanStackQueryClientProvider>
      </body>
    </html>
  );
}
